// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quczzuvsmrnnehlcoxzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Y3p6dXZzbXJubmVobGNveHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNDkyOTQsImV4cCI6MjA3MTYyNTI5NH0.WMdxBGjxb0iNWZqtIGstJa5pZ-5Dyt_o8W4EaduL7r8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});